### ISSUE TITLE
New Project Failed to Compile Error

### ISSUE THREAD

**Issue by hsavit1** [reasonml-old/reason-scripts#76]
Failed to compile

./src/index.re
File "/Users/*****/Desktop/Code/giphy-app/node_modules/reason-react/src/ReactEventRe.re", line 52, characters 4-5:
Error: 2180: <UNKNOWN SYNTAX ERROR>
File "/Users/*****/Desktop/Code/giphy-app/node_modules/reason-react/src/ReactEventRe.re", line 1:
Error: Error while running external preprocessor
Command line: /usr/local/lib/node_modules/bs-platform/bin/refmt3.exe --print binary '/Users/*****/Desktop/Code/giphy-app/node_modules/reason-react/src/ReactEventRe.re' > /var/folders/t6/chlvzpdx0nb_98w5m29x90s80000gn/T/ocamlppe9088a

This error occurred during the build time and cannot be dismissed.

**Comment by hsavit1** [comment]
I tried to build with `yarn start`

**Comment by hsavit1** [comment]
I also tried reinstalling a global bs-platform. then it started spitting out a new error

./src/index.re
Module build failed: Error: [0/18] Building src/ReactEvent.mliast[0/18] Building src/ReactEvent.mlast[0/18] Building src/ReasonReact.mliast[0/18] Building src/ReasonReact.mlast[0/18] Building src/ReactEventRe.mliast[0/18] Building src/ReactEventRe.mlast[0/18] Building src/ReactDOMServerRe.mlast[0/18] Building src/ReasonReactOptimizedCreateClass.mlast[0/18] Building src/ReactDOMRe.mlast[1/18] Building src/ReasonReact.mliast[1/18] Building src/ReasonReact.mliast.d[2/18] Building src/ReactDOMServerRe.mlast[2/18] Building src/ReactDOMServerRe.mlast.d[3/18] Building src/ReasonReactOptimizedCreateClass.mlast[3/18] Building src/ReasonReactOptimizedCreateClass.mlast.d[4/18] Building src/ReactEvent.mliast[4/18] Building src/ReactEvent.mliast.d[5/18] Building src/ReactEvent.mlast[5/18] Building src/ReactEvent.mlast.d[6/18] Building src/ReactEventRe.mlast[6/18] Building src/ReactEventRe.mlast.d[7/18] Building src/ReasonReact.mlast[7/18] Building src/ReasonReact.mlast.d[8/18] Building src/ReactEventRe.mliast[8/18] Building src/ReactEventRe.mliast.d[9/18] Building src/ReasonReact.mliast.d[10/18] Building src/ReactDOMServerRe.mlast.d[11/18] Building src/ReactEvent.mliast.d[12/18] Building src/ReasonReact.mlast.d[13/18] Building src/ReactEventRe.mlast.d[14/18] Building src/ReasonReactOptimizedCreateClass.mlast.d[15/18] Building src/ReactEvent.mlast.d[16/18] Building src/ReactEventRe.mliast.d[17/18] Building src/ReactDOMRe.mlast[17/18] Building src/ReactDOMRe.mlast.d[18/18] Building src/ReactDOMRe.mlast.d
[0/9] Building src/ReactEvent.cmi[0/9] Building src/ReasonReact.cmi[0/9] Building src/ReasonReactOptimizedCreateClass.cmj[1/9] Building src/ReasonReactOptimizedCreateClass.cmj[2/9] Building src/ReasonReact.cmi[2/9] Building src/ReasonReact.cmj[3/9] Building src/ReactEvent.cmi[3/9] Building src/ReactEvent.cmj[3/9] Building src/ReactEventRe.cmi[4/9] Building src/ReactEvent.cmj[5/9] Building src/ReactEventRe.cmi[5/9] Building src/ReactEventRe.cmj[6/9] Building src/ReasonReact.cmj[6/9] Building src/ReactDOMRe.cmj[6/9] Building src/ReactDOMServerRe.cmj[7/9] Building src/ReactDOMServerRe.cmj[8/9] Building src/ReactEventRe.cmj[9/9] Building src/ReactDOMRe.cmj
[0/4] Building src/jest.mliast[0/4] Building src/jest.mlast[1/4] Building src/jest.mliast[1/4] Building src/jest.mliast.d[2/4] Building src/jest.mlast[2/4] Building src/jest.mlast.d[3/4] Building src/jest.mliast.d[4/4] Building src/jest.mlast.d
[0/2] Building src/jest.cmi[1/2] Building src/jest.cmi[1/2] Building src/jest.cmj[2/2] Building src/jest.cmj
[0/6] Building src/App.mlast[0/6] Building src/index.mlast[0/6] Building src/App_test.mlast[1/6] Building src/App.mlast[1/6] Building src/App.mlast.d[2/6] Building src/index.mlast[2/6] Building src/index.mlast.d[3/6] Building src/App_test.mlast[3/6] Building src/App_test.mlast.d[4/6] Building src/index.mlast.d[5/6] Building src/App.mlast.d[6/6] Building src/App_test.mlast.d
[0/3] Building src/App.cmj[0/3] Building src/App_test.cmj[1/3] Building src/App.cmj
/usr/local/lib/node_modules/bs-platform/lib/bsc.exe: don't know what to do with Stuff/giphy-app/node_modules/reason-react/lib/ocaml.
Usage: bsc <options> <files>
Options are:
  -bs-super-errors  Better error message combined with other tools 
  -bs-re-out  Print compiler output in Reason syntax
  -bs-suffix  Set suffix to .bs.js
  -bs-no-implicit-include  Don't include current dir implicitly
  -bs-assume-has-mli  (internal) Assume mli always exist 
  -bs-assume-no-mli  (internal) Don't lookup whether mli exist or not
  -bs-D  Define conditional variable e.g, -D DEBUG=true
  -bs-list-conditionals  List existing conditional variables
  -bs-binary-ast  Generate binary .mli_ast and ml_ast
  -bs-syntax-only  only check syntax
  -bs-no-bin-annot  disable binary annotations (by default on)
  -bs-eval  (experimental) Set the string to be evaluated, note this flag will be conflicted with -bs-main
  -bs-g  debug mode
  -bs-sort-imports  Sort the imports by lexical order so the output will be more stable (default false)
  -bs-no-sort-imports  No sort (see -bs-sort-imports)
  -bs-package-name  set package name, useful when you want to produce npm packages
  -bs-package-map  set package map, not only set package name but also use it as a namespace
  -bs-no-version-header  Don't print version header
  -bs-package-output  set npm-output-path: [opt_module]:path, for example: 'lib/cjs', 'amdjs:lib/amdjs', 'es6:lib/es6' 
  -bs-no-warn-unimplemented-external  disable warnings on unimplmented c externals
  -bs-no-builtin-ppx-ml disable built-in ppx for ml files (internal use)
  -bs-no-builtin-ppx-mli disable built-in ppx for mli files (internal use)
  -bs-cross-module-opt enable cross module inlining(experimental), default(false)
  -bs-diagnose  More verbose output
  -bs-no-check-div-by-zero  unsafe mode, don't check div by zero and mod by zero
  -bs-noassertfalse  no code for assert false
  -bs-main  set the Main entry module in script mode, for example -bs-main Main
  -bs-I  add source dir search path in script mode
  -bs-files  Provide batch of files, the compiler will sort it before compiling
  -impl <file>  Compile <file> as a .ml file
  -intf <file>  Compile <file> as a .mli file
  - <file>  Treat <file> as a file name (even if it starts with `-')
  -absname  Show absolute filenames in error messages
  -annot  Save information in <filename>.annot
  -bin-annot  Save typedtree in <filename>.cmt
  -c  Compile only (do not link)
  -config  Print configuration values and exit
  -g  Save debugging information
  -i  Print inferred interface
  -I <dir>  Add <dir> to the list of include directories
  -color {auto|always|never}  Enable or disable colors in compiler messages
    The following settings are supported:
      auto    use heuristics to enable colors only if supported
      always  enable colors
      never   disable colors
    The default setting is 'auto', and the current heuristic
    checks that the TERM environment variable exists and is
    not empty or "dumb", and that isatty(stderr) holds.
  -intf-suffix <string>  Suffix for interface files (default: .mli)
  -keep-docs  Keep documentation strings in .cmi files
  -keep-locs  Keep locations in .cmi files
  -labels  Use commuting label mode
  -no-alias-deps  Do not record dependencies for module aliases
  -no-app-funct  Deactivate applicative functors
  -noassert  Do not compile assertion checks
  -nolabels  Ignore non-optional labels in types
  -nostdlib  Do not add default directory to the list of include directories
  -o <file>  Set output file name to <file>
  -open <module>  Opens the module <module> before typing
  -pp <command>  Pipe sources through preprocessor <command>
  -ppx <command>  Pipe abstract syntax trees through preprocessor <command>
  -principal  Check principality of type inference
  -rectypes  Allow arbitrary recursive types
  -safe-string  Make strings immutable
  -short-paths  Shorten paths in types
  -strict-sequence  Left-hand part of a sequence must have type unit
  -strict-formats  Reject invalid formats accepted by legacy implementations
     (Warning: Invalid formats may behave differently from
      previous OCaml versions, and will become always-rejected
      in future OCaml versions. You should use this flag
      to detect and fix invalid formats.)
  -unsafe  Do not compile bounds checking on array and string access
  -v  Print compiler version and location of standard library and exit
  -verbose  Print calls to external commands
  -version  Print version and exit
  -vnum  Print version number and exit
  -w <list>  Enable or disable warnings according to <list>:
        +<spec>   enable warnings in <spec>
        -<spec>   disable warnings in <spec>
        @<spec>   enable warnings in <spec> and treat them as errors
     <spec> can be:
        <num>             a single warning number
        <num1>..<num2>    a range of consecutive warning numbers
        <letter>          a predefined set
     default setting is "+a-4-6-7-9-27-29-32..39-41..42-44-45-48-50-102"
  -warn-error <list>  Enable or disable error status for warnings according
     to <list>.  See option -w for the syntax of <list>.
     Default setting is "-a"
  -warn-help  Show description of warning numbers
  -where  Print location of standard library and exit
  -color {auto|always|never}  Enable or disable colors in compiler messages
    The following settings are supported:
      auto    use heuristics to enable colors only if supported
      always  enable colors
      never   disable colors
    The default setting is 'auto', and the current heuristic
    checks that the TERM environment variable exists and is
    not empty or "dumb", and that isatty(stderr) holds.
  -nopervasives  (undocumented)
  -dsource  (undocumented)
  -dparsetree  (undocumented)
  -dtypedtree  (undocumented)
  -drawlambda  (undocumented)
  -dlambda  (undocumented)
  -help  Display this list of options
  --help  Display this list of options
[2/3] Building src/App_test.cmj
/usr/local/lib/node_modules/bs-platform/lib/bsc.exe: don't know what to do with Stuff/giphy-app/node_modules/reason-react/lib/ocaml.
Usage: bsc <options> <files>
Options are:
  -bs-super-errors  Better error message combined with other tools 
  -bs-re-out  Print compiler output in Reason syntax
  -bs-suffix  Set suffix to .bs.js
  -bs-no-implicit-include  Don't include current dir implicitly
  -bs-assume-has-mli  (internal) Assume mli always exist 
  -bs-assume-no-mli  (internal) Don't lookup whether mli exist or not
  -bs-D  Define conditional variable e.g, -D DEBUG=true
  -bs-list-conditionals  List existing conditional variables
  -bs-binary-ast  Generate binary .mli_ast and ml_ast
  -bs-syntax-only  only check syntax
  -bs-no-bin-annot  disable binary annotations (by default on)
  -bs-eval  (experimental) Set the string to be evaluated, note this flag will be conflicted with -bs-main
  -bs-g  debug mode
  -bs-sort-imports  Sort the imports by lexical order so the output will be more stable (default false)
  -bs-no-sort-imports  No sort (see -bs-sort-imports)
  -bs-package-name  set package name, useful when you want to produce npm packages
  -bs-package-map  set package map, not only set package name but also use it as a namespace
  -bs-no-version-header  Don't print version header
  -bs-package-output  set npm-output-path: [opt_module]:path, for example: 'lib/cjs', 'amdjs:lib/amdjs', 'es6:lib/es6' 
  -bs-no-warn-unimplemented-external  disable warnings on unimplmented c externals
  -bs-no-builtin-ppx-ml disable built-in ppx for ml files (internal use)
  -bs-no-builtin-ppx-mli disable built-in ppx for mli files (internal use)
  -bs-cross-module-opt enable cross module inlining(experimental), default(false)
  -bs-diagnose  More verbose output
  -bs-no-check-div-by-zero  unsafe mode, don't check div by zero and mod by zero
  -bs-noassertfalse  no code for assert false
  -bs-main  set the Main entry module in script mode, for example -bs-main Main
  -bs-I  add source dir search path in script mode
  -bs-files  Provide batch of files, the compiler will sort it before compiling
  -impl <file>  Compile <file> as a .ml file
  -intf <file>  Compile <file> as a .mli file
  - <file>  Treat <file> as a file name (even if it starts with `-')
  -absname  Show absolute filenames in error messages
  -annot  Save information in <filename>.annot
  -bin-annot  Save typedtree in <filename>.cmt
  -c  Compile only (do not link)
  -config  Print configuration values and exit
  -g  Save debugging information
  -i  Print inferred interface
  -I <dir>  Add <dir> to the list of include directories
  -color {auto|always|never}  Enable or disable colors in compiler messages
    The following settings are supported:
      auto    use heuristics to enable colors only if supported
      always  enable colors
      never   disable colors
    The default setting is 'auto', and the current heuristic
    checks that the TERM environment variable exists and is
    not empty or "dumb", and that isatty(stderr) holds.
  -intf-suffix <string>  Suffix for interface files (default: .mli)
  -keep-docs  Keep documentation strings in .cmi files
  -keep-locs  Keep locations in .cmi files
  -labels  Use commuting label mode
  -no-alias-deps  Do not record dependencies for module aliases
  -no-app-funct  Deactivate applicative functors
  -noassert  Do not compile assertion checks
  -nolabels  Ignore non-optional labels in types
  -nostdlib  Do not add default directory to the list of include directories
  -o <file>  Set output file name to <file>
  -open <module>  Opens the module <module> before typing
  -pp <command>  Pipe sources through preprocessor <command>
  -ppx <command>  Pipe abstract syntax trees through preprocessor <command>
  -principal  Check principality of type inference
  -rectypes  Allow arbitrary recursive types
  -safe-string  Make strings immutable
  -short-paths  Shorten paths in types
  -strict-sequence  Left-hand part of a sequence must have type unit
  -strict-formats  Reject invalid formats accepted by legacy implementations
     (Warning: Invalid formats may behave differently from
      previous OCaml versions, and will become always-rejected
      in future OCaml versions. You should use this flag
      to detect and fix invalid formats.)
  -unsafe  Do not compile bounds checking on array and string access
  -v  Print compiler version and location of standard library and exit
  -verbose  Print calls to external commands
  -version  Print version and exit
  -vnum  Print version number and exit
  -w <list>  Enable or disable warnings according to <list>:
        +<spec>   enable warnings in <spec>
        -<spec>   disable warnings in <spec>
        @<spec>   enable warnings in <spec> and treat them as errors
     <spec> can be:
        <num>             a single warning number
        <num1>..<num2>    a range of consecutive warning numbers
        <letter>          a predefined set
     default setting is "+a-4-6-7-9-27-29-32..39-41..42-44-45-48-50-102"
  -warn-error <list>  Enable or disable error status for warnings according
     to <list>.  See option -w for the syntax of <list>.
     Default setting is "-a"
  -warn-help  Show description of warning numbers
  -where  Print location of standard library and exit
  -color {auto|always|never}  Enable or disable colors in compiler messages
    The following settings are supported:
      auto    use heuristics to enable colors only if supported
      always  enable colors
      never   disable colors
    The default setting is 'auto', and the current heuristic
    checks that the TERM environment variable exists and is
    not empty or "dumb", and that isatty(stderr) holds.
  -nopervasives  (undocumented)
  -dsource  (undocumented)
  -dparsetree  (undocumented)
  -dtypedtree  (undocumented)
  -drawlambda  (undocumented)
  -dlambda  (undocumented)
  -help  Display this list of options
  --help  Display this list of options    at Array.map (<anonymous>)

**Comment by hsavit1** [comment]
I've also tried the @next branch and that didn't work either

**Comment by rrdelaney** [comment]
@hsavit1 try using Parcel and Reason. reason-scripts isn’t supported anymore.
